name: "Xrob File Converter"
version: "1.0.1"
slug: "xrob_file_converter"

description: "Self-hosted file converter supporting 1000+ formats"

url: "https://github.com/C4illin/ConvertX"

arch:
  - amd64
  - aarch64

startup: application
boot: auto
init: false

ports:
  3000/tcp: 3001

ports_description:
  3000/tcp: "ConvertX Web Interface"

webui: "http://[HOST]:[PORT:3001]"

panel_icon: mdi:file-swap
panel_title: "Xrob File Converter"

map:
  - type: data
    read_only: false

environment:
  JWT_SECRET: "XrobConvertX-2026-8f4c91a72e6b3d5c0a9f"
  ACCOUNT_REGISTRATION: "true"
  AUTO_DELETE_EVERY_N_HOURS: "24"
  MAX_CONVERT_PROCESS: "2"
  LANGUAGE: "en"
  HTTP_ALLOWED: "true"
  TZ: "Africa/Casablanca"
