name: "Xrob File Converter"
version: "1.0.0"
slug: "xrob_file_converter"

description: "Private file converter for documents, images, PDF, audio and video."

url: "https://github.com/ahmedxrob/ai-project"

arch:
  - amd64

startup: application
boot: auto
init: false

ports:
  3000/tcp: 3001

ports_description:
  3000/tcp: "Xrob File Converter Web Interface"

webui: "http://[HOST]:[PORT:3001]"

panel_icon: mdi:file-swap
panel_title: "File Converter"

map:
  - type: data
    read_only: false

environment:
  TZ: "Africa/Casablanca"
